(function(){'use strict';
const TABLE=Object.freeze({width:2,height:1,ballRadius:0.028,pocketRadius:0.064,maxSpeed:2.55,friction:0.43,ballRestitution:0.985,cushionRestitution:0.88,dt:1/240,maxTime:14});
const POCKETS=Object.freeze([{x:0,y:0},{x:1,y:0},{x:2,y:0},{x:0,y:1},{x:1,y:1},{x:2,y:1}]);
const clone=v=>structuredClone(v),clamp=(v,min,max)=>Math.max(min,Math.min(max,Number(v)||0));
function speed(b){return Math.hypot(b.vx,b.vy)}
function tryPocket(ball){if(ball.pocketed)return false;for(let i=0;i<POCKETS.length;i++){const p=POCKETS[i];if(Math.hypot(ball.x-p.x,ball.y-p.y)<=TABLE.pocketRadius){ball.pocketed=true;ball.pocketIndex=i;ball.vx=ball.vy=0;return true}}return false}
function cushion(ball){if(ball.pocketed)return;const r=TABLE.ballRadius,w=TABLE.width,h=TABLE.height;if(ball.x<r){ball.x=r;ball.vx=Math.abs(ball.vx)*TABLE.cushionRestitution}else if(ball.x>w-r){ball.x=w-r;ball.vx=-Math.abs(ball.vx)*TABLE.cushionRestitution}if(ball.y<r){ball.y=r;ball.vy=Math.abs(ball.vy)*TABLE.cushionRestitution}else if(ball.y>h-r){ball.y=h-r;ball.vy=-Math.abs(ball.vy)*TABLE.cushionRestitution}}
function collide(a,b){if(a.pocketed||b.pocketed)return;let dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy),min=TABLE.ballRadius*2;if(!dist||dist>=min)return;const nx=dx/dist,ny=dy/dist,overlap=min-dist;a.x-=nx*overlap*.5;a.y-=ny*overlap*.5;b.x+=nx*overlap*.5;b.y+=ny*overlap*.5;const rel=(b.vx-a.vx)*nx+(b.vy-a.vy)*ny;if(rel>=0)return;const impulse=-(1+TABLE.ballRestitution)*rel/2;a.vx-=impulse*nx;a.vy-=impulse*ny;b.vx+=impulse*nx;b.vy+=impulse*ny}
function friction(ball,dt){if(ball.pocketed)return;const s=speed(ball);if(!s)return;const ns=Math.max(0,s-TABLE.friction*dt);if(ns<.006){ball.vx=ball.vy=0;return}const k=ns/s;ball.vx*=k;ball.vy*=k}
function simulateShot(inputBalls,angle,power,{captureFrames=true}={}){const balls=clone(inputBalls).map(b=>({...b,vx:0,vy:0})),cue=balls.find(b=>b.id===0);if(!cue||cue.pocketed)return{balls,frames:[],duration:0};power=clamp(power,.05,1);const v=TABLE.maxSpeed*(.16+.84*power);cue.vx=Math.cos(angle)*v;cue.vy=Math.sin(angle)*v;const dt=TABLE.dt,maxSteps=Math.ceil(TABLE.maxTime/dt),sampleEvery=Math.max(1,Math.round((1/60)/dt)),frames=[];let settled=0,t=0;if(captureFrames)frames.push({t:0,balls:balls.map(b=>[b.id,b.x,b.y,b.pocketed?1:0])});for(let step=1;step<=maxSteps;step++){t=step*dt;for(const b of balls)if(!b.pocketed){b.x+=b.vx*dt;b.y+=b.vy*dt}for(const b of balls)tryPocket(b);for(const b of balls)cushion(b);for(let pass=0;pass<2;pass++)for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++)collide(balls[i],balls[j]);for(const b of balls)friction(b,dt);if(captureFrames&&step%sampleEvery===0)frames.push({t,balls:balls.map(b=>[b.id,b.x,b.y,b.pocketed?1:0])});const max=Math.max(...balls.filter(b=>!b.pocketed).map(speed),0);if(max<.012)settled+=dt;else settled=0;if(settled>.18)break}for(const b of balls){b.vx=0;b.vy=0}return{balls,frames,duration:t}}
window.TDBPoolPhysics={TABLE,POCKETS,simulateShot,clamp};
})();
